# Basic
title: Bawn
subtitle: Nothing is impossible to a willing heart
# welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
# description: Vno Jekyll is a port of my Ghost theme vno.
creator: <a href="http://onev.cat">@onevcat</a>

url: "http://bawn.github.io/"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: 博客
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: 关于, description: 关于, url: './about'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    # disqus: bawn
    duoshuo: bawn

# Social
social:
    weibo: lingchen0621
    github: bawn
    # twitter: onevcat
    # gplus: 107108267983477358170
    mail: lc5491137@gmail.com

# Google Analytics
ga:
    id: UA-58774091-1
    host: https://bawn.github.io/
